"""HTTP route registration for op助手."""

from aiohttp import web

from ai.server.handlers import api as h
from ai.server.handlers import phase2 as phase2_handlers
from ai.server.routes.agents import register_agent_routes


def register_routes(app: web.Application, *, json_response) -> None:
  register_agent_routes(app, json_response=json_response)

  app.router.add_get("/api/ai/bootstrap", h.api_bootstrap)
  app.router.add_get("/api/ai/status", h.api_status)
  app.router.add_get("/api/ai/providers", h.api_providers)
  app.router.add_get("/api/ai/config", h.api_get_config)
  app.router.add_post("/api/ai/config", h.api_post_config)
  app.router.add_get("/api/ai/models", h.api_models)
  app.router.add_post("/api/ai/models", h.api_models)
  app.router.add_get("/api/ai/test_connection", h.api_test_connection)
  app.router.add_post("/api/ai/test_connection", h.api_test_connection)
  app.router.add_get("/api/ai/test", h.api_test_connection)
  app.router.add_post("/api/ai/test", h.api_test_connection)
  app.router.add_post("/api/ai/chat", h.api_chat)
  app.router.add_get("/api/ai/chat/jobs", h.api_chat_jobs)
  app.router.add_post("/api/ai/chat/jobs", h.api_chat_jobs)
  app.router.add_get("/api/ai/chat/jobs/{job_id}", h.api_chat_job_detail)
  app.router.add_delete("/api/ai/chat/jobs/{job_id}", h.api_chat_job_detail)
  app.router.add_post("/api/ai/shell", h.api_shell)
  app.router.add_get("/api/ai/state", h.api_state)
  app.router.add_get("/api/ai/usage", h.api_usage)
  app.router.add_get("/api/ai/skills", h.api_skills)
  app.router.add_post("/api/ai/skills", h.api_skills)
  app.router.add_get("/api/ai/tools", h.api_tools_meta)
  app.router.add_get("/api/ai/memory", h.api_memory)
  app.router.add_post("/api/ai/memory", h.api_memory)
  app.router.add_get("/api/ai/scheduler", h.api_scheduler)
  app.router.add_post("/api/ai/scheduler", h.api_scheduler)
  app.router.add_get("/api/ai/write/pending", h.api_write_pending)
  app.router.add_post("/api/ai/write/confirm", h.api_write_confirm)
  app.router.add_get("/api/ai/tune_passport", h.api_tune_passport)
  app.router.add_get("/api/ai/rag", h.api_rag)
  app.router.add_post("/api/ai/rag", h.api_rag)
  app.router.add_get("/api/ai/sessions", h.api_sessions)
  app.router.add_post("/api/ai/sessions", h.api_sessions)
  app.router.add_get("/api/ai/dev-assets", h.api_dev_assets)
  app.router.add_get("/api/ai/dev-assets/{kind}/{name}", h.api_dev_assets)
  app.router.add_get("/api/ai/pc-sessions", h.api_pc_sessions)
  app.router.add_get("/api/ai/workflows", h.api_workflows)
  app.router.add_get("/api/ai/notifications", h.api_notifications)
  app.router.add_post("/api/ai/notifications", h.api_notifications)
  app.router.add_get("/api/ai/adaptation/{project_id}/bundle", h.api_adaptation_bundle)
  app.router.add_get("/api/ai/package/version", h.api_package_version)
  app.router.add_post("/api/ai/package/update", h.api_package_update)
  app.router.add_get("/api/ai/fork/detect", h.api_fork_detect)
  app.router.add_post("/api/ai/fork/analyze", h.api_fork_analyze)
  app.router.add_post("/api/ai/fork/sync", h.api_fork_sync)
  app.router.add_post("/api/ai/fork/run", h.api_fork_run_stream)
  app.router.add_post("/api/ai/onboarding/complete", h.api_onboarding_complete)
  app.router.add_post("/api/ai/integrate", h.api_integrate_openpilot)
  app.router.add_get("/api/ai/device/trust", phase2_handlers.api_device_trust)
  app.router.add_post("/api/ai/device/pair", phase2_handlers.api_device_pair)
  app.router.add_delete("/api/ai/device/{device_id}", phase2_handlers.api_device_revoke)
  app.router.add_get("/api/ai/canvas", phase2_handlers.api_canvas)
  app.router.add_get("/api/ai/workspace", phase2_handlers.api_workspace)
  app.router.add_post("/api/ai/workspace", phase2_handlers.api_workspace_write)
  app.router.add_get("/api/ai/usage/detail", phase2_handlers.api_usage_detail)
  app.router.add_get("/api/ai/sessions/search", phase2_handlers.api_platform_sessions_search)
  app.router.add_get("/api/ai/mcp", phase2_handlers.api_platform_mcp)
  app.router.add_post("/api/ai/mcp", phase2_handlers.api_platform_mcp)
  app.router.add_get("/api/ai/learned-skills", phase2_handlers.api_platform_learned_skills)
  app.router.add_post("/api/ai/learned-skills", phase2_handlers.api_platform_learned_skills)
  app.router.add_get("/api/ai/toolsets", phase2_handlers.api_platform_toolsets)
  app.router.add_post("/api/ai/scheduler/nl", phase2_handlers.api_scheduler_nl)
